MySQL:
  Host: 127.0.0.1
  Port: '3306'
  Database: BUNGEE
  Username: minecraft
  Password: z@3S@JAub2pQ8F5T
Prefix:
  Enabled: true
  Rank1: '&c&lADMIN &c'
  Rank2: '&a&lLEITUNG &a'
  Rank3: '&e&lDEVELOPER &e'
  Rank4: '&2SRMOD &2'
  Rank5: '&2&lMOD &2'
  Rank6: '&3&lSUPPORTER &3'
  Rank7: '&9&lHELFER &9'
  Rank8: '&5&lMEDIA &5'
  Rank9: '&b&lDIAMANT &b'
  Rank10: '&e&lGOLD &e'
  Rank11: '&f&lEISEN &f'
  Rank12: '&7&lSPIELER &7'
  Clantagformat: ' &7[&e%clantag%&7]'
Chat:
  Enabled: true
  Format:
    InClan: '&7[&e%clantag%&7] &7%prefix%%player% &8» &f%message%'
    NoClan: '&7%prefix%%player% &8» &f%message%'
