name: MMOLobby
version: 1.4
author: NotJan
main: de.notjan.mmolobby.main.Main
commands:
  build:
    description: Aktiviere/Deaktivier den Baumodus!
  lobby:
    description: Lobby-Setup
  plugins:
    aliases: pl
    description: Zeigt alle benutzten Plugins auf dem Server!
  stop:
    description: Stoppt den Server!
  vanish:
    description: Setzt dich in den Vanish!
    permission: lobby.vanish
    aliases: v
  s:
    description: Server-Command für den Navigator